// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	CountCustomers(ctx context.Context) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, id int32) error
	GetCustomer(ctx context.Context, id int32) (Customer, error)
	GetCustomerByPhone(ctx context.Context, phone string) (Customer, error)
	GetCustomerForPreview(ctx context.Context, id int32) (GetCustomerForPreviewRow, error)
	GetCustomersByLocation(ctx context.Context, arg GetCustomersByLocationParams) ([]Customer, error)
	GetCustomersByPreferredProduct(ctx context.Context, arg GetCustomersByPreferredProductParams) ([]Customer, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	SearchCustomersByName(ctx context.Context, arg SearchCustomersByNameParams) ([]Customer, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerPreferredProduct(ctx context.Context, arg UpdateCustomerPreferredProductParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
