// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	CountCampaigns(ctx context.Context, arg CountCampaignsParams) (int64, error)
	// campaigns.sql
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	GetCampaign(ctx context.Context, id int32) (Campaign, error)
	GetCampaignStats(ctx context.Context, campaignID int32) (GetCampaignStatsRow, error)
	GetCampaignsReadyToSend(ctx context.Context) ([]GetCampaignsReadyToSendRow, error)
	ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error)
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateCampaignToSending(ctx context.Context, id int32) (Campaign, error)
}

var _ Querier = (*Queries)(nil)
