// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type Campaign struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	Channel      string       `json:"channel"`
	Status       string       `json:"status"`
	ScheduledAt  sql.NullTime `json:"scheduled_at"`
	BaseTemplate string       `json:"base_template"`
	CreatedAt    time.Time    `json:"created_at"`
}

type CampaignSendJob struct {
	ID                int32          `json:"id"`
	OutboundMessageID int32          `json:"outbound_message_id"`
	CampaignID        int32          `json:"campaign_id"`
	Status            string         `json:"status"`
	Attempts          int32          `json:"attempts"`
	LastError         sql.NullString `json:"last_error"`
	ScheduledFor      time.Time      `json:"scheduled_for"`
	ProcessedAt       sql.NullTime   `json:"processed_at"`
	CreatedAt         time.Time      `json:"created_at"`
}

type Customer struct {
	ID              int32          `json:"id"`
	Phone           string         `json:"phone"`
	Firstname       string         `json:"firstname"`
	Lastname        string         `json:"lastname"`
	Location        sql.NullString `json:"location"`
	PreferedProduct sql.NullString `json:"prefered_product"`
	CreatedAt       time.Time      `json:"created_at"`
}

type OutboundMessage struct {
	ID                int32          `json:"id"`
	CampaignID        int32          `json:"campaign_id"`
	CustomerID        int32          `json:"customer_id"`
	Status            string         `json:"status"`
	RenderedContent   string         `json:"rendered_content"`
	LastError         sql.NullString `json:"last_error"`
	RetryCount        int32          `json:"retry_count"`
	ProviderMessageID sql.NullString `json:"provider_message_id"`
	SentAt            sql.NullTime   `json:"sent_at"`
	FailedAt          sql.NullTime   `json:"failed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
