// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	CountOutboundMessagesByCampaign(ctx context.Context, campaignID int32) (int64, error)
	CreateOutboundMessage(ctx context.Context, arg CreateOutboundMessageParams) (OutboundMessage, error)
	CreateOutboundMessageBatch(ctx context.Context, arg CreateOutboundMessageBatchParams) ([]OutboundMessage, error)
	GetFailedMessagesWithRetry(ctx context.Context, arg GetFailedMessagesWithRetryParams) ([]OutboundMessage, error)
	GetOutboundMessage(ctx context.Context, id int32) (OutboundMessage, error)
	GetOutboundMessageWithDetails(ctx context.Context, id int32) (GetOutboundMessageWithDetailsRow, error)
	GetPendingMessagesForCampaign(ctx context.Context, arg GetPendingMessagesForCampaignParams) ([]OutboundMessage, error)
	UpdateOutboundMessageStatus(ctx context.Context, arg UpdateOutboundMessageStatusParams) (OutboundMessage, error)
	UpdateOutboundMessageWithRetry(ctx context.Context, arg UpdateOutboundMessageWithRetryParams) (OutboundMessage, error)
}

var _ Querier = (*Queries)(nil)
